# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 827a2ffa960d4ff2668e3c303cd9180ac16c0212279e849624ed475d3025fedc2b8dfdb477863f601fc8893a913211b78dd44300841c07301b9ac9aea6ea5065

test:
  secret_key_base: 806c17875ff6a89e2226f64082ff27772ab92739494a894544b0c0e29c0f2cd76d620b51d128522201ced3dd2640f51e7027233ae09fa036856d36f98e70495f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
